### ISSUE TITLE
UI&UX: Tampilan Button pada Form Detailtransaksi

### ISSUE THREAD

**Issue by zdnabrhm** [Mezzky/apotiku#33]
button di semua form detail transaksi harus pakek input type submit, biar datanya mau ke kirim, otomatis css yang buat button ga bisa buat pakek di sintak input, jadinya cacad tampilannya
![image](https://user-images.githubusercontent.com/95616202/203015805-f98206ee-fb88-4a3d-83f6-217cad403bfa.png)
![image](https://user-images.githubusercontent.com/95616202/203015909-c880047d-57b6-4bab-a78d-66e094e7b3ab.png)
kek gitu jadinya
@Mezzky

**Comment by zdnabrhm** [comment]
Oiya sama ini
![image](https://user-images.githubusercontent.com/95616202/203016552-06ac6dff-8fa9-4e11-b6d7-e0ac3cf08d8d.png)
inputnya pakek datalist bukan select option, jadi cssnya gak jalan

**Comment by Mezzky** [comment]
Kasi Class form-data di formnya @danzBraham

**Comment by zdnabrhm** [comment]
oiya ci, dh bisa ternyata

**Comment by zdnabrhm** [comment]
![image](https://user-images.githubusercontent.com/95616202/203017161-961e3406-e412-4906-82f5-37d5ae37eb53.png)
tapi masi agak cacad buttonnya soalnya bukan pakek button

**Comment by Mezzky** [comment]
Otw benerin
