### ISSUE TITLE
UI: Tampilan Print Kureng

### ISSUE THREAD

**Issue by zdnabrhm** [Mezzky/apotiku#34]
![image](https://user-images.githubusercontent.com/95616202/203022846-b3baaa7a-81c3-4fc7-8911-ab08c423d769.png)
text di thead gedein ama kasi bgcolor pas diprint biar uxnya joss
@Mezzky

**Comment by Mezzky** [comment]
Dibilang, warna ga kebaca

**Comment by Mezzky** [comment]
Bold in ja tu theadnya

**Comment by zdnabrhm** [comment]
atur" dah, ntar aku tinggal pull
